# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_random_supplierrandom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='customers',
            field=models.ManyToManyField(related_name='providers', to='places.Place'),
        ),
    ]
