# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_squashed_0004_auto_20170418_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_img', models.ImageField(upload_to=b'books/')),
            ],
        ),
    ]
