# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='cover_img',
            field=models.ImageField(upload_to=b'books'),
        ),
    ]
