# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
