# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170418_2144'),
    ]

    operations = [
    ]
