# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
